apiVersion: v1
kind: ConfigMap
metadata:
  name: config-spring-cloud-k8s-example
data:
  application.properties: |-
    welcome.message.hello=Hello Labs from app.properties
    message=Hi from app.yml
